### ISSUE TITLE
Vespawatch model

### ISSUE THREAD

**Issue by stevegerrits** [inbo/vespa-db#1]
Field | Type | Description
-- | -- | --
id | integer [primary key] |  
creation_datetime | datetime | Creation datetime of the db object. This is to make a distinction between the reporter date and the import date for bulk imports
reporter_phone_number | Optional[str] | phone nr of reporter. Optionally, due to phone_nr not a required field on waarnemingen.be users login.
reporter_email | str | email of reporter
source  | SourceEnum | can be ObservationsAPI, User or Import
reported_datetime | datetime | reporter date
location | GisPointField | location of the nest
status | NestStatusEnum | status can be Untreated or Treated
visible | bool (default true) | true/false: admin can change this to remove nests from the map
images | List[str] | list of image file names on the s3 bucket
nature_reserve | bool | true/false
public_domain | bool | true=public, false=private
exterminator_id | users.id | link to the exterminator user
extermination_datetime | datetime | datetime of extermination
modification_datetime | datetime | or last_modification_datetime, datetime of the current db object version.

**Comment by peterdesmet** [comment]
- `reporter_id`: reporters are not going to be Django users, so not sure we need this. Would only be used if the nest was created by the admin in the Django admin interface.
- `deleted`: would not have this if we already have `visible`
- `extermination_info`: remove, there will be more specialized fields than this
- `version_datetime`: I prefer `modification_datetime`
- `source`: I think this should be added, with enum [Waarnemingen, User, Import]

**Comment by peterdesmet** [comment]
For (Django) users, we won't need:

- `phone_number`
- `approved`
- `deleted`

We will need:

- `name`

**Comment by stevegerrits** [comment]
I also removed the role field from users model. As django has the is_superuser built-in

**Comment by PietrH** [comment]
Peter asked me for an overview of the fields currently in iAsset, the simplest answer is:

|id  |fieldtype         |fieldlabel                  |length |field_order |dependent_field |dependent_option_id |dependent_option_value |options                                |
|:---|:-----------------|:---------------------------|:------|:-----------|:---------------|:-------------------|:----------------------|:--------------------------------------|
|435 |current_user      |Geregistreerd door          |50     |1           |                |                    |                       |NULL                                   |
|436 |datetime          |Datum tijd registratie      |50     |1           |                |                    |                       |NULL                                   |
|437 |date              |Datum observatie            |50     |1           |                |                    |                       |NULL                                   |
|438 |text              |Adres                       |255    |1           |                |                    |                       |NULL                                   |
|439 |location          |Coördinaten van het nest    |50     |1           |                |                    |                       |NULL                                   |
|440 |select            |Nesthoogte                  |50     |1           |                |                    |                       |lager dan 4 meter                      |
|440 |select            |Nesthoogte                  |50     |1           |                |                    |                       |hoger dan 4 meter                      |
|441 |select            |Nestgrootte                 |50     |1           |                |                    |                       |minder dan 25 cm                       |
|441 |select            |Nestgrootte                 |50     |1           |                |                    |                       |meer dan 25 cm                         |
|442 |select            |Nestplaats                  |50     |1           |                |                    |                       |buiten, onbedekt op gebouw             |
|442 |select            |Nestplaats                  |50     |1           |                |                    |                       |buiten, onbedekt in boom of struik     |
|442 |select            |Nestplaats                  |50     |1           |                |                    |                       |buiten, maar overdekt door constructie |
|442 |select            |Nestplaats                  |50     |1           |                |                    |                       |buiten, natuurlijk overdekt            |
|442 |select            |Nestplaats                  |50     |1           |                |                    |                       |binnen, in gebouw of constructie       |
|442 |select            |Nestplaats                  |50     |1           |                |                    |                       |ongekend                               |
|443 |textarea          |Opmerkingen                 |5000   |1           |                |                    |                       |NULL                                   |
|447 |field_group       |Melding                     |50     |1           |                |                    |                       |NULL                                   |
|448 |photo             |Foto nest 1                 |50     |1           |                |                    |                       |NULL                                   |
|449 |photo             |Foto nest 2                 |50     |1           |                |                    |                       |NULL                                   |
|450 |photo             |Foto nest 3                 |50     |1           |                |                    |                       |NULL                                   |
|461 |radio             |Gevalideerd                 |50     |1           |                |                    |                       |nee                                    |
|461 |radio             |Gevalideerd                 |50     |1           |                |                    |                       |ja                                     |
|462 |radio             |Nesttype                    |50     |1           |461             |1370                |02                     |AH - actief embryonaal nest            |
|462 |radio             |Nesttype                    |50     |1           |461             |1370                |02                     |AH - actief primair nest               |
|462 |radio             |Nesttype                    |50     |1           |461             |1370                |02                     |AH - actief secundair nest             |
|462 |radio             |Nesttype                    |50     |1           |461             |1370                |02                     |AH - inactief/leeg nest                |
|462 |radio             |Nesttype                    |50     |1           |461             |1370                |02                     |AH - potentieel nest (meer info nodig) |
|462 |radio             |Nesttype                    |50     |1           |461             |1370                |02                     |nest andere soort                      |
|462 |radio             |Nesttype                    |50     |1           |461             |1370                |02                     |geen nest (object, insect)             |
|463 |radio             |Feedback bezorgd            |50     |1           |461             |1370                |02                     |nee                                    |
|463 |radio             |Feedback bezorgd            |50     |1           |461             |1370                |02                     |ja                                     |
|465 |text              |Andere soort                |5000   |1           |462             |1377                |06                     |NULL                                   |
|466 |radio             |Beheerd                     |50     |1           |461             |1370                |02                     |nee                                    |
|466 |radio             |Beheerd                     |50     |1           |461             |1370                |02                     |ja                                     |
|466 |radio             |Beheerd                     |50     |1           |461             |1370                |02                     |onbekend                               |
|467 |radio             |Duplicaat                   |50     |1           |461             |1370                |02                     |nee                                    |
|467 |radio             |Duplicaat                   |50     |1           |461             |1370                |02                     |ja                                     |
|468 |radio             |Publiek domein              |50     |1           |461             |1370                |02                     |onbekend                               |
|468 |radio             |Publiek domein              |50     |1           |461             |1370                |02                     |ja                                     |
|468 |radio             |Publiek domein              |50     |1           |461             |1370                |02                     |nee                                    |
|469 |textarea          |validatie opmerking         |5000   |1           |461             |1370                |02                     |NULL                                   |
|485 |radio             |Bestrijding gestart         |50     |1           |                |                    |                       |nee                                    |
|485 |radio             |Bestrijding gestart         |50     |1           |                |                    |                       |ja                                     |
|486 |datetime          |Datum en tijd bestrijding   |50     |1           |485             |1479                |02                     |NULL                                   |
|487 |number            |Tijd ter plaatse            |50     |1           |485             |1479                |02                     |NULL                                   |
|488 |number            |Aantal personen             |50     |1           |485             |1479                |02                     |NULL                                   |
|489 |current_user      |Gerapporteerd door          |50     |1           |485             |1479                |02                     |NULL                                   |
|490 |textarea          |Bestrijding opmerking       |5000   |1           |485             |1479                |02                     |NULL                                   |
|491 |select            |Resultaat                   |50     |1           |485             |1479                |02                     |succesvol behandeld                    |
|491 |select            |Resultaat                   |50     |1           |485             |1479                |02                     |niet succesvol behandeld               |
|491 |select            |Resultaat                   |50     |1           |485             |1479                |02                     |niet behandeld                         |
|491 |select            |Resultaat                   |50     |1           |485             |1479                |02                     |onbekend                               |
|492 |select            |Problemen                   |50     |1           |485             |1479                |02                     |geen                                   |
|492 |select            |Problemen                   |50     |1           |485             |1479                |02                     |steken                                 |
|492 |select            |Problemen                   |50     |1           |485             |1479                |02                     |nest gevallen                          |
|492 |select            |Problemen                   |50     |1           |485             |1479                |02                     |duizeligheid/misselijkheid             |
|492 |select            |Problemen                   |50     |1           |485             |1479                |02                     |gif projectie                          |
|492 |select            |Problemen                   |50     |1           |485             |1479                |02                     |onbekend                               |
|493 |select            |Nazorg                      |50     |1           |485             |1479                |02                     |nest volledig verwijderd               |
|493 |select            |Nazorg                      |50     |1           |485             |1479                |02                     |nest gedeeltelijk verwijderd           |
|493 |select            |Nazorg                      |50     |1           |485             |1479                |02                     |nest laten hangen                      |
|493 |select            |Nazorg                      |50     |1           |485             |1479                |02                     |onbekend                               |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |Permas-D                               |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |vloeibare stikstof                     |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |Vespa Ficam D                          |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |Topscore PAL                           |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |ether/aceton/ethyl acetate             |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |diatomeënaarde                         |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |andere                                 |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |geen                                   |
|494 |select            |Product                     |50     |1           |485             |1479                |02                     |onbekend                               |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |diepvries                              |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |telescoopsteel                         |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |afsluitbaar potje/doos                 |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |vloeistof verstuiver                   |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |poeder verstuiver                      |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |niet behandeld                         |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |andere                                 |
|495 |select            |Methode                     |50     |1           |485             |1479                |02                     |onbekend                               |
|496 |text              |Bestrijder                  |255    |1           |485             |1479                |02                     |NULL                                   |
|497 |text              |Dossiernummer verdelging    |255    |1           |485             |1479                |02                     |NULL                                   |
|498 |photo             |Foto bestrijding            |50     |1           |485             |1479                |02                     |NULL                                   |
|500 |radio             |Gelegen binnen ANB gebied   |50     |1           |501             |1529                |02                     |onbekend                               |
|500 |radio             |Gelegen binnen ANB gebied   |50     |1           |501             |1529                |02                     |ja                                     |
|500 |radio             |Gelegen binnen ANB gebied   |50     |1           |501             |1529                |02                     |nee                                    |
|501 |radio             |Coördinatie gestart         |50     |1           |                |                    |                       |nee                                    |
|501 |radio             |Coördinatie gestart         |50     |1           |                |                    |                       |ja                                     |
|502 |radio             |Te bestrijden door overheid |50     |1           |501             |1529                |02                     |onbekend                               |
|502 |radio             |Te bestrijden door overheid |50     |1           |501             |1529                |02                     |ja                                     |
|502 |radio             |Te bestrijden door overheid |50     |1           |501             |1529                |02                     |nee                                    |
|503 |select_inspectors |Aangeduide bestrijder       |50     |1           |501             |1529                |02                     |NULL                                   |
|505 |current_user      |Validator                   |5000   |1           |461             |1370                |02                     |NULL                                   |
|534 |select            |E-mail versturen            |50     |1           |501             |1529                |02                     |Versturen per mail                     |
|534 |select            |E-mail versturen            |50     |1           |501             |1529                |02                     |NIET versturen per mail                |
|535 |radio             |Provincie                   |50     |1           |461             |1370                |02                     |West-Vlaanderen                        |
|535 |radio             |Provincie                   |50     |1           |461             |1370                |02                     |Oost-Vlaanderen                        |
|535 |radio             |Provincie                   |50     |1           |461             |1370                |02                     |Antwerpen                              |
|535 |radio             |Provincie                   |50     |1           |461             |1370                |02                     |Vlaams-Brabant                         |
|535 |radio             |Provincie                   |50     |1           |461             |1370                |02                     |Limburg                                |
|535 |radio             |Provincie                   |50     |1           |461             |1370                |02                     |niet Vlaanderen                        |
|535 |radio             |Provincie                   |50     |1           |461             |1370                |02                     |ongekend                               |
|536 |radio             |Bezorgd_administratie       |50     |1           |501             |1529                |02                     |ja                                     |
|536 |radio             |Bezorgd_administratie       |50     |1           |501             |1529                |02                     |nee                                    |
|537 |number            |Autonummer                  |50     |1           |                |                    |                       |NULL                                   |
|444 |text              |Naam                        |255    |2           |                |                    |                       |NULL                                   |
|445 |text              |Telefoon                    |50     |2           |                |                    |                       |NULL                                   |
|446 |text              |E-mailadres                 |255    |2           |                |                    |                       |NULL                                   |
|460 |field_group       |Validatie                   |50     |2           |                |                    |                       |NULL                                   |
|504 |field_group       |Coördinatie                 |50     |3           |                |                    |                       |NULL                                   |
|499 |field_group       |Bestrijding                 |50     |4           |                |                    |                       |NULL                                   |
|451 |checkbox          |Toestemming gegevensgebruik |50     |14          |                |                    |                       |NULL                                   |

Made via `iassetR::get_fields()`, this does not translate 100% to the Web interface, or the Excel imports, but rather is what the iAsset API returns. 

Multiple rows for multiple values, because that is what was practical for the R package. 

Let me know if I can provide anything else. I can try to dig up the documentation if needed (but I suspect changes were made and the documentation not updated).
